### ISSUE TITLE
Cannot use urlmanager in config.php

### ISSUE THREAD

**Issue by avinasx** [asasmoyo/yii2-saml#37]
```
$urlManager = Yii::$app->urlManager;
$spBaseUrl = $urlManager->getHostInfo() . $urlManager->getBaseUrl();
```

I tried to put SAML configuration in the component array of config.php

but it won't work.
the error log of apache2 shows the following:

` Trying to get property 'urlManager' of non-object in /Library/WebServer/Documents/**/config/web.php on line 8, referer: http://localhost/**/web/index.php/site/login
[Mon Apr 27 17:14:28.972965 2020] [php7:error] [pid 20918] [client ::1:52479] PHP Fatal error:  Uncaught Error: Call to a member function getHostInfo() on null `

**Comment by asasmoyo** [comment]
i'm not following Yii2 nowadays, but it seems like `Yii::$app->urlManager` is not accessible from config anymore. if it's the case then probably you have to parse data from `$_SERVER` instead, or simply hardcode the url

**Comment by avinasx** [comment]
Thanks for the suggestions.

**Comment by juliardi** [comment]
It may be late but I may found what the problem is. There are 2 ways of including the SAML configuration in this library. The first is by setting a config path in `configFileName`, like this
```php
'saml' => [
            'class' => 'asasmoyo\yii2saml\Saml',
            'configFileName' => '@common/config/saml.php',
        ],
```
The second one is by directly assigning an array to `config` key, like this
```php
'saml' => [
            'class' => 'asasmoyo\yii2saml\Saml',
            'config' => [
                'sp' => [
                    // sp config here
                ],
                'idp' => [
                    // idp config here
                ],
            ],
        ]
```
If we use the first option, by setting a filepath alias to `configFileName`, the URL Manager is accessible and can be used to generate URL. Even the `yii\helpers\Url` works here. 
But, if we use the second option, the URL Manager can't be used and we must generate the URL manually.
